export const softwareKeywords = [".NET", ".NET Development", "AJAX", "APIs", "ASP.NET", "User Interface (UI) Development", "Algorithms", "Amazon Web Server (AWS)", "Amazon Web Services (AWS)", "Android", "TypeScript", "Relational Databases", "Elasticsearch", "Hibernate (Java)", "Neuro-Linguistic Programming (NLP)", "Redux", "Responsive Web Design", "Android App Development", "Angular 2.0", "Angular 7.0", "Angular.js Development", "AngularJS", "Apache", "LOVE for Lua Game Development", "Microsoft Dynamics CRM", "Artificial Intelligence (AI)", "Artificial intelligence", "Backend Development", "Blockchain", "Blockchain Development", "Bootstrap", "C Programming", "C#", "C#.NET", "C++ Programming", "CMS", "CRM", "CSS", "Cloud Computing", "Cloud Firestore", "CodeIgniter", "Computer Networking", "Computer Networks", "Computer Science", "Computer Vision", "Data Structures", "Database Building", "Database Testing", "Deep Learning", "DevOps", "DigitalOcean", "Django", "Docker", "ERP Implementation and Deployment", "ExpressJS", "Firebase", "Flask", "Fortran", "Frontend Development", "Full Stack Development", "Game Development", "Game Testing", "Git", "Github", "HTML", "JSP", "Java", "Java Enterprise Edition", "JavaFX", "JavaScript", "JavaScript Frameworks", "Joomla", "jQuery", "JSON", "Kotlin", "LISP Programming", "Laravel Framework", "Linux", "Lua Programming", "MEAN Stack", "MS SQL Server", "Mobile App Development", "Mobile Application Testing", "MongoDB", "MySQL", "NGINX", "Node.js", "Oracle", "PHP", "PLC Programming", "Pascal Programming", "Perl Programming", "Personal Development", "PostgreSQL", "Power Query", "PowerApps", "Python", "Python Numpy", "Python Pandas", "R Programming", "RESTful API", "React Native", "React.js", "SQL", "SQL Programming", "SQLite", "Software Development", "Software Testing", "Stripe Payment API", "Tailwind CSS", "VS Code", "Web Development", "Wireframing", "WordPress", "Wordpress Development", "iOS", "iOS App Development", "jQuery", "Windows Mobile Application Development", "Selenium", "Dart", "ElectronJS", "Ember.js", "IBM AS/400", "IBM Cloud", "IBM SPSS", "Internet of Things (IoT)", "Ionic Framework", "Jasmine Framework", "Load Testing", "Machine Learning", "Microsoft Azure", "NoSQL", "OS Installation", "PLC Programming", "RESTful API", "RTL Coding", "Ruby Programming", "XML", "Xcode"];

export const webDevKeywords = ["Frontend Development", "Backend Development", "Full Stack Development"];

export const graphicKeywords = ["3ds Max", "Adobe After Effects", "Adobe Audition", "Adobe Creative Suite", "Adobe Dreamweaver", "Adobe Fireworks", "Adobe Flash", "Adobe Illustrator", "Adobe Indesign", "Adobe Photoshop", "Adobe Photoshop Lightroom CC", "Adobe Premiere Pro", "Adobe XD", "AutoCAD", "Autodesk 123D design", "Autodesk Alias", "Autodesk Fusion 360", "Autodesk Inventor", "Autodesk Maya", "Autodesk Revit", "Autodesk SketchBook", "Blender 3D", "CAD", "CAD Design", "Vector Dynamics", "CorelDRAW", "Design", "Design Thinking", "Digital Art", "FPGA Design", "Fashion Designing", "Figma", "Graphic Design", "Home Design", "Illustration", "Photo Editing", "Photography", "Photoshop", "Presentation Skills", "Product Design", "Sketch", "Sketching", "Jewellery Design", "UI & UX Design", "UI/UX Design", "UX Research", "Unity 3D", "3D Printing", "Canva", "Circuit Design", "BIM (Building Information Modeling)", "Colour Theory for Designers", "Creative Design", "Culinary Arts", "Game Design", "Motion Graphics", "Multimedia"];

export const datascienceKeywords = ["Data Analysis", "Machine Learning", "Statistical Analysis", "Data Mining", "Predictive Modeling", "Big Data", "Data Visualization", "Python", "R Programming", "SQL", "Natural Language Processing (NLP)", "Deep Learning", "Artificial Intelligence (AI)", "Data Engineering", "Data Warehousing", "Business Intelligence (BI)", "Data Cleaning", "Feature Engineering", "Time Series Analysis", "Regression Analysis", "Clustering", "Classification", "Dimensionality Reduction", "Exploratory Data Analysis (EDA)", "Data Preprocessing", "Hypothesis Testing", "Random Forest", "Gradient Boosting", "Neural Networks", "Support Vector Machines (SVM)", "K-means Clustering", "Linear Regression", "Logistic Regression", "Decision Trees", "Apache Spark", "Hadoop", "TensorFlow", "Keras", "Scikit-learn", "Pandas", "NumPy", "Matplotlib", "Seaborn", "Tableau", "D3.js", "Power BI", "Data Science Ethics", "Data Privacy", "Data Governance", "A/B Testing", "Feature Selection", "Model Evaluation", "Cross-Validation", "Ensemble Learning", "Time Series Forecasting", "Data Journalism", "Data Storytelling"];

export const marketingKeywords = ["Analytics", "Big Data", "Big Data Analytics", "Content Marketing", "Data Analysis", "Data Analytics", "Digital Advertising", "Digital Marketing", "Display Advertising", "Facebook Advertising", "Google AdWords", "Google Analytics", "Google Cloud Platform", "Google Tag Manager", "Google Web Toolkit", "Market Research", "Marketing Analytics", "Marketing Strategy", "PPC", "Public Relations (PR)", "SEO", "Search Engine Marketing (SEM)", "Search Engine Optimization (SEO)", "Social Media Marketing", "Brand Management", "Business Analysis", "Business Development", "Business Research", "Business/MBA", "Financial Analysis", "Instagram Marketing", "Magento", "Mailchimp", "Malware Analysis", "Network Analysis", "Operations Management", "Pinterest Marketing", "Predictive Analytics", "Product Management", "Project Management", "Project Planning", "YouTube Ads"];

export const financeKeywords = ["Financial Analysis", "Investment Banking", "Portfolio Management", "Risk Management", "Financial Modeling", "Accounting", "Auditing", "Corporate Finance", "Financial Planning", "Budgeting", "Taxation", "Banking Operations", "Credit Analysis", "Equity Research", "Mergers and Acquisitions", "Venture Capital", "Private Equity", "Hedge Funds", "Asset Management", "Derivatives Trading", "Compliance", "Insurance", "Financial Reporting", "Valuation", "Securities Trading", "Fixed Income", "Treasury Management", "Financial Risk", "Fintech", "Financial Services", "Quantitative Finance", "Economic Analysis", "Financial Markets", "Investor Relations", "Wealth Management", "Financial Advisory", "Credit Risk", "Commercial Banking", "Investment Management", "Cash Management", "Financial Compliance", "Financial Statements", "Financial Regulation", "Financial Operations", "Financial Accounting", "Financial Engineering", "Financial Auditing", "Financial Forecasting"];

export const businessdevelopmentKeywords = ["Sales", "Marketing", "Lead Generation", "Client Acquisition", "Customer Relationship Management (CRM)", "Market Research", "Strategic Planning", "Business Strategy", "Partnership Development", "Negotiation", "Proposal Writing", "Account Management", "B2B Sales", "B2C Sales", "Cold Calling", "Networking", "Consultative Selling", "Pipeline Management", "Revenue Growth", "Customer Retention", "Competitive Analysis", "Value Proposition", "Sales Forecasting", "Relationship Building", "Brand Management", "Product Management", "Market Segmentation", "Market Penetration", "Channel Development", "Key Account Management", "Contract Negotiation", "Sales Presentations", "Strategic Partnerships", "E-commerce", "Business Development Strategy", "Client Servicing", "Cross-selling", "Upselling", "Customer Satisfaction", "Market Expansion", "Distribution Channels", "Sales Enablement", "Lead Qualification", "Customer Acquisition Cost (CAC)", "Customer Lifetime Value (CLV)", "Sales Metrics", "Sales Operations", "Sales Training", "Business Development Planning", "Deal Closing"];

export const editingKeywords = ["Audacity", "Audio Editing", "Audio Making", "Audio Making/Editing", "Video Editing", "Video Making", "Video Making/Editing", "Animation", "Maya"];

export const contentwritingKeyowords = ["Content Creation", "Copywriting", "Article Writing", "Blog Writing", "SEO Writing", "Web Content", "Social Media Content", "Creative Writing", "Editing", "Proofreading", "Content Marketing", "Technical Writing", "Ghostwriting", "Content Strategy", "Email Marketing", "Press Release Writing", "White Paper Writing", "Content Management", "Content Optimization", "Copy Editing", "Storytelling", "Narrative Writing", "Journalism", "Research Writing", "Academic Writing", "Scriptwriting", "Video Scriptwriting"];

export const humanresourcesKeywords = ["Recruitment", "Talent Acquisition", "HR Management", "Employee Relations", "Performance Management", "Training and Development", "Compensation and Benefits", "Organizational Development", "HR Policies", "Workforce Planning", "Succession Planning", "HRIS (Human Resource Information System)", "Employee Engagement", "Onboarding", "Offboarding", "Labor Relations", "Employee Training", "Employee Retention", "HR Compliance", "Payroll Management", "Career Development", "Diversity and Inclusion", "HR Analytics", "Job Analysis", "Workforce Diversity", "Employee Satisfaction", "HR Consulting", "Workplace Safety", "Employment Law", "HR Administration", "Interviewing", "Background Checks"];






export const languageKeywords = ["American English", "Bengali Proficiency (Spoken)", "Bengali Proficiency (Written)", "Bodo Proficiency(Spoken)", "Bodo Proficiency(Written)", "British English", "Dogri Proficiency(Spoken)", "Dogri Proficiency(Written)", "Effective Communication", "English Proficiency (Spoken)", "English Proficiency (Written)", "English translation", "German Proficiency (Spoken)", "German Proficiency (Written)", "Gujarati Proficiency (Spoken)", "Gujarati Proficiency (Written)", "Hindi Proficiency (Spoken)", "Hindi Proficiency (Written)", "Indonesian Proficiency (Spoken)", "Indonesian Proficiency (Written)", "Italian Proficiency (Spoken)", "Italian Proficiency (Written)", "Latvian Proficiency (Spoken)", "Latvian Proficiency (Written)", "Malay Proficiency (Spoken)", "Assamese Proficiency (Spoken)", "Malay Proficiency (Written)", "Portuguese Proficiency (Spoken)", "Portuguese Proficiency (Written)", "Public Speaking", "Punjabi Proficiency (Spoken)", "Punjabi Proficiency (Written)", "Sanskrit Proficiency (spoken)", "Sanskrit Proficiency (written)", "Tamil Proficiency (Spoken)", "Tamil Proficiency (Written)", "Telugu Proficiency (Spoken)", "Telugu Proficiency (Written)", "Urdu Proficiency(Written)"];

export const actingKeywords = ["Acting", "Acting Audition", "Acting technique", "Anchoring", "Blogging", "Cinema 4D", "Cinematography", "Film Production", "Videography", "Voice-over artist", "Voiceover"];


export const subjectKeywords = ["Aerospace Engineering", "Accounts", "Agriculture & Food Engineering", "Biology", "Biotechnology Engineering", "Chemical Engineering", "Chemistry", "Civil Engineering", "Commerce", "Data Science", "Economics", "Ergonomics", "Electrical Engineering", "Electronics", "Environment Science", "Psychology", "Genetic Engineering", "Geology", "Government Exams", "Information Technology", "Matlab", "Mechanical Engineering", "Mechatronics Engineering", "Ethical Hacking", "Physics", "Science", "Subject Matter Expert (SME)", "Teaching", "Bioinformatics", "Biostatistics", "Numerical Analysis", "Forensic Science", "GATE", "Go Language", "IELTS", "MBA", "Medicine", "Narration", "Olympiad", "Quantitative Analysis", "Research Papers", "Statistics"];

export const servicesKeywords = ["Auditing", "Bank", "Campus Ambassador", "Chartered Accountancy (CA)", "Client Relationship", "Client Servicing", "Client interaction", "Company Secretary (CS)", "Travel & Tourism", "Compensation management", "Customer Service", "Cyber Security", "Employee Relations", "Entrepreneurship", "Event Management", "Feedback Management", "Financial Reporting", "General Ledger Accounting", "Ghostwriting", "HR Consulting", "HR Management", "Human Resource Management (HR)", "IT Service Management", "Information Security", "LAN Management", "Leadership", "Learning and Development", "Legal Compliance", "Legal Research", "Life Skills Coaching", "Linux System Administration", "Lyric Writing", "Office Administration", "Online Writing", "Personal Development", "Real Estate", "Recruitment", "Report Writing", "SYSTEM ADMINISTRATOR", "Salesforce", "Stock Trading", "Stock/Market Trading", "Talent Acquisition", "Telecalling", "Time Management", "Training and Development", "Supply Chain Management (SCM)", "Tally", "Enterprise Architecture", "Food Production", "Foreign Exchange", "Fundraising", "Geographic Information System (GIS)", "Insurance", "Lean Management", "Management Consulting", "Manufacturing Design", "Mental Health Counseling", "Mentoring", "Microservices", "Network Security", "Objective-C", "Organizational Behavior", "Outbound Sales", "Payroll Processing", "Policy Analysis", "Problem Solving", "Product Sourcing", "Proofreading", "Quality Assurance (QA)", "Quality Management", "Red Hat Certified Engineer (RHCE)", "SAS", "Sales pitch", "Sass", "SharePoint", "Social Work", "SolidWorks", "Storyboarding", "Strategy", "Statutory compliances"];

export const electronicsKeywords = ["ARM Microcontroller", "Analog And Digital Circuits", "Architecture", "Arduino", "Embedded C", "Embedded Systems", "Engineering Design", "Industrial Design", "Instructional Design", "Home Automation", "Image Processing", "Microcontroller Programming", "OCR Tesseract", "Robotics", "LAN", "Digital Signal Processing"];

export const skillsKeywords = ["Advanced Excel", "Transcription", "Translation", "Articulate Storyline", "Content Writing", "Copywriting", "Creative Writing", "Data Entry", "Editorial", "Feature Writing", "Handwriting Analysis", "Interior Design", "Managerial Skills", "Personal Branding", "Sports", "Volunteering", "Physical Fitness", "Piano Performance", "Media Management", "Pitch Deck", "Product Photography", "Resin Art", "MS Office", "Microsoft Excel", "Microsoft Office", "Microsoft Outlook", "Microsoft PowerPoint", "Microsoft SQL Server", "Microsoft Teams", "Microsoft Visio", "Microsoft Word", "PowerApps"];
